# Generated by Django 5.0.3 on 2024-03-09 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='reting',
            new_name='rating',
        ),
    ]
